version: '3.8'
services:
  # postgres:
  #   image: postgres
  #   environment:
  #     - POSTGRES_PASSWORD=mysecretpassword
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  backend:
    build:
      context: .
      dockerfile: docker/Dockerfile.backend
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=${DATABASE_URL}
    # depends_on:
    #   - postgres
  frontend:
    build:
      context: .
      dockerfile: docker/Dockerfile.frontend
      
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
    # depends_on:
    #   - backend
  ws:
    build:
      context: .
      dockerfile: docker/Dockerfile.ws
    ports:
      - "8081:8081"
    environment:
      - DATABASE_URL=${DATABASE_URL}
    # depends_on:
    #   - postgres

 

# volumes:
#   postgres_data:



 
